### ISSUE TITLE
Moar cookie powerups

### ISSUE THREAD

**Issue by jt4uc** [jt4uc/MfC#23]
Also keep track of which cookies you've collected

**Comment by ayz7bs** [comment]
2 cookies for sure: 1 to allow the mower to have a stop option, another to widen the mower's "mowing range". I can explain more in person, but since we're doing pokemon ice level style, we need to widen the available grass the mower can get to ensure they mow enough.

**Comment by ayz7bs** [comment]
Idea: instead of widening the mower the 'mowable' range, what if we have cookies that switch the move style from pokemon ice level to what we currently have? this will help deal with the 'is traversed' part of it if we can't get that cookie boost working.
