### ISSUE TITLE
Change how levels are represented

### ISSUE THREAD

**Issue by ayz7bs** [jt4uc/MfC#3]

**Comment by jt4uc** [comment]
Tiled. It allows us to make levels according to a grid system without specifying specify pixel locations. We can also specify collisions.

**Comment by ayz7bs** [comment]
Is that what it's currently able to do? What's our status on level designing with XML stuff?

**Comment by jt4uc** [comment]
Status: still working on it. Tiled unfortunately doesn't have much documentation and it's been difficult to work it into C# or Visual Studio specifically, because it's such a general library.

**Comment by jt4uc** [comment]
Integrate Tiled more. Focus on how enemies are represented in tiled - keep the small array format.
