### ISSUE TITLE
Cookie class

### ISSUE THREAD

**Issue by ayz7bs** [jt4uc/MfC#5]

**Comment by ayz7bs** [comment]
Started. I've created int x, y, fuel, Spot s, and String type for it. Made a constructor. Changed Spot to accommodate Cookie. Updated MainGame to hardcode a Cookie in it.

**Comment by ayz7bs** [comment]
Get framework working

**Comment by jt4uc** [comment]
Note to self: Cookie class refers to powerups

**Comment by jt4uc** [comment]
The powerup we have: Grandma moves faster
